### ISSUE TITLE
[Eclipse+IntelliJ] ACR -> Too many follow-up request:21

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#1137]
My repro steps:

1. Open an ACR explorer with enabled state firstly
2. Then Disable admin user
3. Push image using this disabled acr
4. After getting error, enable the acr, error just like below picture

![image](https://user-images.githubusercontent.com/22470312/31705545-65fc994e-b418-11e7-81fd-a927c81d06ec.png)
5. When loading repositories, an error pops up
![image](https://user-images.githubusercontent.com/22470312/31705446-fe9be110-b417-11e7-8440-8881590d2c1b.png)
Even if you click OK, the current  acr explorer will not work properly unless you reopen the acr explorer

**Comment by jdneo** [comment]
This issue can also be reproduced on Azure portal, steps:

1. open an ACR which enables admin user on Azure portal.
2. disable it (In Access Keys setting panel)
3. try to push image onto this ACR (of cause it will fail due to unauthorized issue)
4. enable it (In Access Keys setting panel)
5. open the Repositories panel, an error occurred.

screenshot:
<img width="863" alt="screen shot 2017-10-19 at 4 04 52 pm" src="https://user-images.githubusercontent.com/6193897/31760445-512b723a-b47a-11e7-9d4f-2d7f4ccc054a.png">

**Comment by jdneo** [comment]
This is because the registry service caches “whether admin user is enabled” for up to one minute due to performance optimization. So if the reproducing steps we mentioned above is conducted very quickly, this issue will occur. Otherwise, if the user do it 'slowly' enough, the repos and tags can be listed correctly. 

So I think what we can do here is to pop up more meaningful error message to tell the user what is happening.

**Comment by jdneo** [comment]
The fix changes the error message to tell the user retry it when listing is failed. @bsaby You can verify this in the new build, thanks.

**Comment by bsaby** [comment]
Test passed. Build used: dev447
New error message shown as below:
Eclipse
![image](https://user-images.githubusercontent.com/22470312/31807685-26522fe4-b5a2-11e7-84b0-f29b398e1bfe.png)
IntelliJ
![image](https://user-images.githubusercontent.com/22470312/31807705-3f68e0ea-b5a2-11e7-8b57-d2eda0800136.png)
