### ISSUE TITLE
Latest toolset release incompatable with older Eclipse releases

### ISSUE THREAD

**Issue by duanewaninger** [Microsoft/azure-tools-for-java#17]
The Marketplace description for Azure Toolkit for Eclipse 2.9.0 indicates the plugin is compatible with the following Eclipse versions:

"Eclipse Versions: Neon (4.6), Mars (4.5), Luna (4.4), Kepler (4.3), Juno (4.2, 3.8), Previous to Juno (<=4.1)"

However, the latest release updated on "2016-06-07 14:15" has introduced a dependency on bundle org.eclipse.jdt.ui 3.10.0.  Exact error message is:

Cannot complete the install because one or more required items could not be found.
  Software being installed: Azure Explorer for Eclipse 1.0.0.201607081824 (com.microsoft.azureexplorer.feature.feature.group 1.0.0.201607081824)
  Missing requirement: Azure Common Plugin Library 2.9.1.201607081824 (com.microsoftopentechnologies.wacommon 2.9.1.201607081824) requires 'bundle org.eclipse.jdt.ui 3.10.0' but it could not be found
  Cannot satisfy dependency:
    From: Azure Explorer Plugin for Eclipse 1.0.0.201607081824 (com.microsoft.azureexplorer 1.0.0.201607081824)
    To: bundle com.microsoftopentechnologies.wacommon 2.9.1
  Cannot satisfy dependency:
    From: Azure Explorer for Eclipse 1.0.0.201607081824 (com.microsoft.azureexplorer.feature.feature.group 1.0.0.201607081824)
    To: com.microsoft.azureexplorer [1.0.0.201607081824]

**Comment by pednekarprajakta** [comment]
Marketplace description needs to be updated. Azure Toolkit for Eclipse 2.9.1 is compatible with Neon (4.6), Mars (4.5) and Luna (4.4)

**Comment by duanewaninger** [comment]
These are significant changes for such a minor point release (2.9.0 --> 2.9.1).  Any thoughts on following a more typical versioning pattern and not introducing major breaking changes in minor point releases?

**Comment by martinsawicki** [comment]
yes, unfortunately the Eclipse pre-req change was a last minute call we had to make due to the discovery of unexpected challenges with older versions of Eclipse in some of the newly implemented features. 
Overall though, for better of worse, the plugin versioning has been kept in synch with the Azure SDK versioning, so that it'd be clear which version of the SDK is the plugin's pre-req. So the v2.9.1 of the plugin is simply inherited from the Azure SDK v2.9.1 release. 
Having said that, the Azure SDK and Azure Toolkit of Eclipse have been growing increasingly independent of each other, so there may be a time in the future where the two versioning schemes may part ways, if that's what winds up making more sense eventually.

**Comment by martinsawicki** [comment]
updated the marketplate pre-reqs and latest version
