### ISSUE TITLE
Eclipse Mars.2 Azure Plugin - we don't properly cleanup the old plugin

### ISSUE THREAD

**Issue by milismsft** [Microsoft/azure-tools-for-java#188]
<img width="1764" alt="screen shot 2017-03-17 at 10 20 31 am" src="https://cloud.githubusercontent.com/assets/15163996/24055049/d2fdc57a-0afb-11e7-9ab9-64a0a41a9990.png">

**Comment by martinsawicki** [comment]
Because of the IDs changing for some of the components in the v3.0, Eclipse is not able to do a clean upgrade. So we will need to tell users to uninstall *everything* (including the upgraded/new components) and reinstall from http://dl.microsoft.com/eclipse.
The error message should list all the names of the components that come from the Toolkit and will show up in the Installed Software dialog (old and new):

"You have an older version of the Azure Toolkit for Eclipse installed which could not be automatically upgraded. You should uninstall all the listed components manually, and reinstall from http://dl.microsoft.com/eclipse"

- component A
- component B. .... etc.

(Reiley suggested assigning to Rome)

**Comment by andxu** [comment]
![image](https://cloud.githubusercontent.com/assets/17075863/24233582/23b682e6-0fce-11e7-9ee1-7073e0987bf8.png)

**Comment by andxu** [comment]
Will popup a dialog like above.
