### ISSUE TITLE
Exception Publishing the project to azure from eclipse

### ISSUE THREAD

**Issue by tejakt952** [Microsoft/azure-tools-for-java#2]
There is an  Exception publishing the project to Azure,from eclipse using azure toolkit 2.8.2. it worked for first time,but the subsequent tries failed. i am facing an error when trying to deploy to azure Web App container.
![error](https://cloud.githubusercontent.com/assets/18401025/14433937/f6fa0dbc-ffd5-11e5-9dc8-fbcf07f25475.jpg)

**Comment by pednekarprajakta** [comment]
Could you send .log file ? Log file should be present at <eclipse_workspace_location>\.metadata folder.
We have also released next version i.e. 2.9.0 of toolkit few days back. Check if it works for you.

**Comment by martinsawicki** [comment]
we haven;t heard back on the repro with 2.9.0 so presuming we've fixed it.

**Comment by oliverkleber** [comment]
I have the same problem with 2.9.5. The enum com.microsoft.azure.management.websites.models.RemoteDebuggingVersion has no entry for VS2015. The suggested workaround for similiar errors, to switch on and off remote debugging for all apps does not work for me.
[logfile.txt](https://github.com/Microsoft/azure-tools-for-java/files/532557/logfile.txt)

**Comment by vladimir-shcherbakov** [comment]
Thanks for the comment. Similar issue is #25. The root cause is that Azure provides new values which [azure-sdk-for-java](https://github.com/Azure/azure-sdk-for-java/blob/0.9/service-management/azure-svc-mgmt-websites/src/main/java/com/microsoft/windowsazure/management/websites/models/RemoteDebuggingVersion.java#L29) does not yet know. We are going to release a fix soon.
