### ISSUE TITLE
Cannot see existing webapps in intellij azure toolkit plugin

### ISSUE THREAD

**Issue by oak-tree** [Microsoft/azure-tools-for-java#21]
Hey
I installed `azure-toolkit-for-intellij`  plugin. I want to be able to do remote debugging to one of our exist `webapp`. Note that we do **not** want to use the plugin to deploy the webapp for serveral reasons ( we use custom config -`web.config`, git deployment and etcc )
What we are looking for is an ability to attach a debugger to a working webapp. Is it possible? 

As for the plugin, in the `Azure webapp` `run configuration` I do see my subscription but no webapp is listed ( we have more than 3 webapps). 

Thanks

**Comment by martinsawicki** [comment]
Hi, you are asking two questions:

1) why aren't some webapps showing in Azure explorer --- how did you create these webapps? Using the old Azure portal (or ASM-based API, a.k.a. "Classic") or the new Azure portal (ARM-based)?  If they were created using the old portal (http://manage.windowsazure.com) they were probably created as ASM-based web apps. The Azure Toolkit does not support those old style webapps, only ARM-based ones, i.e. created via the new Azure portal (portal.azure.com). Please check how these webapps were created.

Also, were they created as Java webapps or as .Net webapps explicitly?  If .NET, then they would not be listed in the Tookit's Debug Config UI either, since Java debugging cannot be enabled on them.  They need to be explicitly created as Java webapps (with Java version selected).

2) how to debug a running webapp? --- the webapps (assuming it's an ARM based one per above) would need to be deployed with debugging enabled. Doing this manually involves modifying web.config or enabling websockets via the portal (see https://github.com/Azure/azure-websites-java-remote-debugging). That's what the toolkit does under the hood.  And they need to be created as Java webapps, not .NET.  Once it's configured that way, it should be debuuggable from Eclipse or IntelliJ -- let me know if you still have problems after following those steps.
