### ISSUE TITLE
Sequence contains no elements

### ISSUE THREAD

**Issue by sallyur** [Microsoft/azure-tools-for-java#2263]
Build: 819

Repro steps:

1. Deploy a project to webapp1
2. Delete webapp1, but not in the current window
3. Back to this window and select run on webapp 
4. Select webapp1 and check deploy to slot option

Result:

When it try to get slot data, you will get an error as below:
![image](https://user-images.githubusercontent.com/28860891/47493538-19808000-d882-11e8-8a4b-d1c424c7c855.png)

I think the web app list should be refreshed automatically each time when user open the run on web app window.

**Comment by Eskibear** [comment]
> I think the web app list should be refreshed automatically each time when user open the run on web app window.

No, we cannot. Due to the performance issue, we always need the cache to provide better UX. The root cause is we didn't update the cache after deleting a web app. 

See:

https://github.com/Microsoft/azure-tools-for-java/blob/f202e4f5c0509d5f597bb905c292acb0d47439f0/Utils/azuretools-core/src/com/microsoft/azuretools/core/mvp/model/webapp/AzureWebAppMvpModel.java#L256-L259

@SummerSun Please take some time to complete the above TODO item.

**Comment by SummerSun** [comment]
I took some time to catch up the cache TODO item in PR #2228, I will complete this too.

**Comment by bsaby** [comment]
Test passed.
Build used: Daily558
