### ISSUE TITLE
[IntelliJ][ReportedByUser][log][Spark] Azure Plugin for IntelliJ Error

### ISSUE THREAD

**Issue by dgilling** [microsoft/azure-tools-for-java#2440]
IntelliJ build version: 2018.3.1 IU-183.4588.61
OS: Mac OS X
JDK: JetBrains s.r.o 1.8.0_152-release
Plugin version: 3.15.0-2018.3
Error message: 
```
com.microsoft.azure.hdinsight.spark.common.SparkJobException: The Spark job failed to start due to 18/12/05 21:41:55 INFO ApplicationMaster: Deleting staging directory wasb://moesif-spark@XXXXXXXX.blob.core.windows.net/user/livy/.sparkStaging/application_1542823984994_1573
18/12/05 21:41:55 WARN AzureFileSystemThreadPoolExecutor: Disabling threads for Delete operation as thread count 0 is <= 1
18/12/05 21:41:55 INFO AzureFileSystemThreadPoolExecutor: Time taken for Delete operation is: 16 ms with threads: 0
18/12/05 21:41:55 INFO ShutdownHookManager: Shutdown hook called
18/12/05 21:41:55 INFO MetricsSystemImpl: Stopping azure-file-system metrics system...
18/12/05 21:41:55 INFO MetricsSinkAdapter: azurefs2 thread interrupted.
18/12/05 21:41:55 INFO MetricsSystemImpl: azure-file-system metrics system stopped.
18/12/05 21:41:55 INFO MetricsSystemImpl: azure-file-system metrics system shutdown complete.

Failing this attempt. Failing the application.
	at com.microsoft.azure.hdinsight.spark.common.SparkBatchJob.lambda$awaitStarted$58(SparkBatchJob.java:1252)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:69)
	at rx.internal.operators.OnSubscribeFilter$FilterSubscriber.onNext(OnSubscribeFilter.java:76)
	at rx.internal.operators.OperatorTakeUntilPredicate$ParentSubscriber.onNext(OperatorTakeUntilPredicate.java:61)
	at rx.internal.operators.OnSubscribeRedo$2$1.onNext(OnSubscribeRedo.java:244)
	at rx.internal.operators.OnSubscribeRedo$2$1.onNext(OnSubscribeRedo.java:244)
	at rx.i

**Comment by wezhang** [comment]
Thanks @dgilling! Can the re-try mitigate the issue?

**Comment by wezhang** [comment]
The exception should not be classified as a tool error.

**Comment by sahilrawal** [comment]
Hi, Have we got the solution for the above problem as I am also facing the same while running Spark Job on Azure ?

ERROR: The Spark job failed to start due to 19/12/27 07:51:03 INFO ApplicationMaster: Deleting staging directory wasb://myhdinsightcluster@ijch3fcbydwt2.blob.core.windows.net/user/livy/.sparkStaging/application_1577428256022_0011
19/12/27 07:51:03 WARN AzureFileSystemThreadPoolExecutor: Disabling threads for Delete operation as thread count 0 is <= 1
19/12/27 07:51:03 INFO AzureFileSystemThreadPoolExecutor: Time taken for Delete operation is: 17 ms with threads: 0
19/12/27 07:51:03 INFO ShutdownHookManager: Shutdown hook called
19/12/27 07:51:03 INFO MetricsSystemImpl: Stopping azure-file-system metrics system...
19/12/27 07:51:03 INFO MetricsSinkAdapter: azurefs2 thread interrupted.
19/12/27 07:51:03 INFO MetricsSystemImpl: azure-file-system metrics system stopped.
19/12/27 07:51:03 INFO MetricsSystemImpl: azure-file-system metrics system shutdown complete.

Thanks in advance

**Comment by wezhang** [comment]
@sahilrawal , could you please provide all output of job submission logs? What's your current plugin version?

Thanks!

**Comment by sahilrawal** [comment]
Hello Wei,

Please find attached the submission logs.
Below is the Spark Configuration.

val conf = new SparkConf(true)
  .setAppName("SampleCosmosDBCassandraApp")

  // Cosmos DB Cassandra API Connection configs
  .set("spark.cassandra.connection.host",
"mycassandradb.cassandra.cosmos.azure.com")
  .set("spark.cassandra.connection.port", "10350")
  .set("spark.cassandra.connection.ssl.enabled", "true")
  .set("spark.cassandra.auth.username", "mycassandradb")
  .set("spark.cassandra.auth.password",
"bgpco3trnoYt6ONF0lJ4KLNR5JDzHV4n1WeQzTWfHm18LRc35qQCUkTw2k8KSrclB1HX3oxpQ2kmgBtcbclC0g==")
  // Parallelism and throughput configs.
  .set("spark.cassandra.output.batch.size.rows", "1")
  // *NOTE*: The values below are meant as defaults for a sample
workload. Please read the README.md for more information on fine
tuning these conf value.
  .set("spark.cassandra.connection.connections_per_executor_max", "10")
  .set("spark.cassandra.output.concurrent.writes", "100")
  .set("spark.cassandra.concurrent.reads", "512")
  .set("spark.cassandra.output.batch.grouping.buffer.size", "1000")
  .set("spark.cassandra.connection.keep_alive_ms", "60000")
  // Cosmos DB Connection Factory, configured with retry policy for
rate limiting.
  .set("spark.cassandra.connection.factory",
"com.microsoft.azure.cosmosdb.CosmosDbConnectionFactory")

Plugin Version:

[image: image.png]

Run Configuration:

[image: image.png]


Cluster Configurations:

[image: image.png]



Thanks
Sahil

**Comment by wezhang** [comment]
@sahilrawal, could you fix the images pasted link? looks they are broken.

**Comment by sahilrawal** [comment]
Hello @wezhang ,

IntelliJ IDEA 2019.2.3 (Community Edition)
Build #IC-192.6817.14, built on September 24, 2019
Runtime version: 11.0.4+10-b304.69 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
Non-Bundled Plugins: com.microsoft.tooling.msservices.intellij.azure V- 3.30.0-2019.2

**JOB SUBMISSION LOGS:**

Package and deploy the job to Spark cluster
INFO: Begin uploading file D:\SparkCassandraHDInsightsTest\out\artifacts\SparkCassandraHDInsightsTest_DefaultArtifact\default_artifact.jar to Azure Blob Storage Account wasbs://myhdinsightcluster@ijch3fcbydwt2.blob.core.windows.net/SparkSubmission/2019/12/30/3ee3aa4c-e673-460c-815a-fe64808464be/default_artifact.jar ...
INFO: Submit file to azure blob 'wasbs://myhdinsightcluster@ijch3fcbydwt2.blob.core.windows.net/SparkSubmission/2019/12/30/3ee3aa4c-e673-460c-815a-fe64808464be/default_artifact.jar' successfully.
INFO: Spark Batch submission Response: status [201], content [Created], headers [Content-Type: application/json; charset=UTF-8; Location: /batches/2; request-id: 0bc75870df194bc0abd4d478942797fe; x-ms-hdi-active: hn0-myhdin.z3zt2dcjl11unjd0nef14qhrue.bx.internal.cloudapp.net; x-ms-hdi-http-host: hn0-myhdin.z3zt2dcjl11unjd0nef14qhrue.bx.internal.cloudapp.net:8998; Strict-Transport-Security: max-age=31536000; includeSubDomains; Date: Mon, 30 Dec 2019 07:30:41 GMT; Content-Length: 145], body [{"id":2,"state":"starting","appId":null,"appInfo":{"driverLogUrl":null,"sparkUiUrl":null},"log":["stdout: ","\nstderr: ","\nYARN Diagnostics: "]}]
LOG: SLF4J: Class path contains multiple SLF4J bindings.
LOG: SLF4J: Found binding in [jar:file:/usr/hdp/2.6.5.3016-3/spark2/jars/slf4j-log4j12-1.7.16.jar!/org/slf4j/impl/StaticLoggerBinder.class]
LOG: SLF4J: Found binding in [jar:file:/usr/hdp/2.6.5.3016-3/spark_llap/spark-llap-assembly-1.0.0.2.6.5.3016-3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
LOG: SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
LOG: SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
LOG: Warning: Master yarn-cluster is deprecated since 2.0. Please use master "yarn" with specified deploy mode instead.
LOG: 19/12/30 07:30:43 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
LOG: Warning: Skip remote jar wasbs://myhdinsightcluster@ijch3fcbydwt2.blob.core.windows.net/SparkSubmission/2019/12/30/3ee3aa4c-e673-460c-815a-fe64808464be/default_artifact.jar.
LOG: 19/12/30 07:30:43 INFO MetricsConfig: loaded properties from hadoop-metrics2-azure-file-system.properties
LOG: 19/12/30 07:30:43 INFO WasbAzureIaasSink: Init starting.
LOG: 19/12/30 07:30:43 INFO AzureIaasSink: Init starting. Initializing MdsLogger.
LOG: 19/12/30 07:30:43 INFO AzureIaasSink: Init completed.
LOG: 19/12/30 07:30:43 INFO WasbAzureIaasSink: Init completed.
LOG: 19/12/30 07:30:43 INFO MetricsSinkAdapter: Sink azurefs2 started
LOG: 19/12/30 07:30:43 INFO RequestHedgingRMFailoverProxyProvider: Looking for the active RM in [rm1, rm2]...
LOG: 19/12/30 07:30:44 INFO RequestHedgingRMFailoverProxyProvider: Found active RM [rm2]
LOG: 19/12/30 07:30:44 INFO Client: Requesting a new application from cluster with 2 NodeManagers
LOG: 19/12/30 07:30:44 INFO Client: Verifying our application has not requested more than the maximum memory capability of the cluster (51200 MB per container)
LOG: 19/12/30 07:30:44 INFO Client: Will allocate AM container, with 4480 MB memory including 384 MB overhead
LOG: 19/12/30 07:30:44 INFO Client: Setting up container launch context for our AM
LOG: 19/12/30 07:30:44 INFO Client: Setting up the launch environment for our AM container
LOG: 19/12/30 07:30:44 INFO Client: Preparing resources for our AM container
LOG: 19/12/30 07:30:45 INFO Client: Uploading resource wasbs://myhdinsightcluster@ijch3fcbydwt2.blob.core.windows.net/SparkSubmission/2019/12/30/3ee3aa4c-e673-460c-815a-fe64808464be/default_artifact.jar -> wasb://myhdinsightcluster@ijch3fcbydwt2.blob.core.windows.net/user/livy/.sparkStaging/application_1577687731223_0006/default_artifact.jar
LOG: 19/12/30 07:30:46 INFO SecurityManager: Changing modify acls to: livy
LOG: 19/12/30 07:30:46 INFO SecurityManager: Changing view acls groups to: 
LOG: 19/12/30 07:30:46 INFO SecurityManager: Changing modify acls groups to: 
LOG: 19/12/30 07:30:46 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(livy); groups with view permissions: Set(); users  with modify permissions: Set(livy); groups with modify permissions: Set()
LOG: 19/12/30 07:30:46 INFO Client: Submitting application application_1577687731223_0006 to ResourceManager
LOG: 19/12/30 07:30:46 INFO YarnClientImpl: Submitted application application_1577687731223_0006
LOG: 19/12/30 07:30:46 INFO Client: Application report for application_1577687731223_0006 (state: ACCEPTED)
LOG: 19/12/30 07:30:46 INFO Client: 
LOG: 	 client token: N/A
LOG: 	 diagnostics: [Mon Dec 30 07:30:46 +0000 2019] Application is Activated, waiting for resources to be assigned for AM.  Details : AM Partition = <DEFAULT_PARTITION> ; Partition Resource = <memory:102400, vCores:30> ; Queue's Absolute capacity = 50.0 % ; Queue's Absolute used capacity = 0.0 % ; Queue's Absolute max capacity = 100.0 % ; 
LOG: 	 ApplicationMaster host: N/A
LOG: 	 ApplicationMaster RPC port: -1
LOG: 	 queue: default
LOG: 	 start time: 1577691046495
LOG: 	 final status: UNDEFINED
LOG: 	 tracking URL: http://hn1-myhdin.z3zt2dcjl11unjd0nef14qhrue.bx.internal.cloudapp.net:8088/proxy/application_1577687731223_0006/
LOG: 	 user: livy
LOG: 19/12/30 07:30:46 INFO ShutdownHookManager: Shutdown hook called
LOG: 19/12/30 07:30:46 INFO ShutdownHookManager: Deleting directory /tmp/spark-3efc8463-cc1d-4a11-8b42-69941dccba30
LOG: 19/12/30 07:30:46 INFO ShutdownHookManager: Deleting directory /tmp/spark-c16a90d7-ca6c-4824-89f6-ceb7422a39a7
LOG: AM container is launched, waiting for AM container to Register with RM
ERROR: The Spark job failed to start due to 19/12/30 07:31:03 INFO ApplicationMaster: Deleting staging directory wasb://myhdinsightcluster@ijch3fcbydwt2.blob.core.windows.net/user/livy/.sparkStaging/application_1577687731223_0006
19/12/30 07:31:04 WARN AzureFileSystemThreadPoolExecutor: Disabling threads for Delete operation as thread count 0 is <= 1
19/12/30 07:31:04 INFO AzureFileSystemThreadPoolExecutor: Time taken for Delete operation is: 16 ms with threads: 0
19/12/30 07:31:04 INFO ShutdownHookManager: Shutdown hook called
19/12/30 07:31:04 INFO MetricsSystemImpl: Stopping azure-file-system metrics system...
19/12/30 07:31:04 INFO MetricsSinkAdapter: azurefs2 thread interrupted.
19/12/30 07:31:04 INFO MetricsSystemImpl: azure-file-system metrics system stopped.
19/12/30 07:31:04 INFO MetricsSystemImpl: azure-file-system metrics system shutdown complete.

Failing this attempt. Failing the application.

**SPARK CONFIGURATION:**


val conf = new SparkConf(true)
  .setAppName("SampleCosmosDBCassandraApp")

  // Cosmos DB Cassandra API Connection configs
  .set("spark.cassandra.connection.host",
"mycassandradb.cassandra.cosmos.azure.com")
  .set("spark.cassandra.connection.port", "10350")
  .set("spark.cassandra.connection.ssl.enabled", "true")
  .set("spark.cassandra.auth.username", "mycassandradb")
  .set("spark.cassandra.auth.password",
"bgpco3trnoYt6ONF0lJ4KLNR5JDzHV4n1WeQzTWfHm18LRc35qQCUkTw2k8KSrclB1HX3oxpQ2kmgBtcbclC0g==")
  // Parallelism and throughput configs.
  .set("spark.cassandra.output.batch.size.rows", "1")
  // *NOTE*: The values below are meant as defaults for a sample
workload. Please read the README.md for more information on fine
tuning these conf value.
  .set("spark.cassandra.connection.connections_per_executor_max", "10")
  .set("spark.cassandra.output.concurrent.writes", "100")
  .set("spark.cassandra.concurrent.reads", "512")
  .set("spark.cassandra.output.batch.grouping.buffer.size", "1000")
  .set("spark.cassandra.connection.keep_alive_ms", "60000")
  // Cosmos DB Connection Factory, configured with retry policy for
rate limiting.
  .set("spark.cassandra.connection.factory",
"com.microsoft.azure.cosmosdb.CosmosDbConnectionFactory")




**POM.xml**

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>sample</groupId>
    <artifactId>sample</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <spark.version>2.4.0</spark.version>
        <scala.version.major>2.11</scala.version.major>
        <scala.version.minor>12</scala.version.minor>
        <scala.version>${scala.version.major}.${scala.version.minor}</scala.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.apache.spark</groupId>
            <artifactId>spark-core_${scala.version.major}</artifactId>
            <version>${spark.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.spark</groupId>
            <artifactId>spark-sql_${scala.version.major}</artifactId>
            <version>${spark.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.spark</groupId>
            <artifactId>spark-streaming_${scala.version.major}</artifactId>
            <version>${spark.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.spark</groupId>
            <artifactId>spark-mllib_${scala.version.major}</artifactId>
            <version>${spark.version}</version>
        </dependency>
        <dependency>
            <groupId>org.jmockit</groupId>
            <artifactId>jmockit</artifactId>
            <version>1.34</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.datastax.spark</groupId>
            <artifactId>spark-cassandra-connector_2.11</artifactId>
            <version>2.0.6</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>net.alchim31.maven</groupId>
                <artifactId>scala-maven-plugin</artifactId>
                <version>3.2.2</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>compile</goal>
                            <goal>testCompile</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <scalaVersion>${scala.version}</scalaVersion>
                </configuration>
            </plugin>
            <plugin>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.3</version>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>

Thanks
Sahil

**Comment by wezhang** [comment]
@sahilrawal, from your logs provided, the Spark job has been submitted into cluster successfully (the client tool side job is finished). And there was a new Yarn application created: `application_1577687731223_0006`. I'd like to suggest to check this application logs from Yarn UI to find out the root cause.

Thanks
