### ISSUE TITLE
[IntelliJ] not able to create New App Service Plan

### ISSUE THREAD

**Issue by JialinXin** [Microsoft/azure-tools-for-java#274]
Location is blank and no available item to select break the operation.
![image](https://cloud.githubusercontent.com/assets/15338714/24188719/676033ea-0f1d-11e7-8d48-227c9e9e8a81.png)

**Comment by martinsawicki** [comment]
this is a known issue in the currently public release as it turns out what shows up here depends on subscription type, and some subscription types turn out not to work in the old implementation of the Java SDK. But this should work fine in the new v3 version --- it looks like you're not using that, but the publicly released version?

**Comment by JialinXin** [comment]
Yes. The tests and issues are toward the public plugin. I will have a try for the new version. Thanks for clarifying.
