### ISSUE TITLE
Spark 2.0  Failed to submit to spark cluster. error code : 502, reason : Bad Gateway.

### ISSUE THREAD

**Issue by ThomTel** [Microsoft/azure-tools-for-java#29]
When i try to submit a spark job from IntelliJ to a Spark 2.0 HDInsight Cluster i get the following eeror: 

 Failed to submit to spark cluster. error code : 502, reason : Bad Gateway.

Submiting to Spark 1.6 Cluster works fine. 

Regards, 

Thomas

**Comment by visionalsky** [comment]
Hi Thom, The tool did not support Spark 2.0 now. It needs to connect to spark cluster via livy service. However, livy service haven't been supported on Spark 2.0 HDInsight Cluster. So that is why the tool can not support Spark 2.0 for now. The service team is still working on it and the EAT is early Nov. We will have an update to support Spark 2.0 after that.

Thank you.

**Comment by ThomTel** [comment]
Hi Zhenbo, 

this sounds feasible. Then i will wait for it. 

Thanks

Thomas
