### ISSUE TITLE
Docker host details are not accurate when key vault is not being used

### ISSUE THREAD

**Issue by aovechki** [Microsoft/azure-tools-for-java#325]
win10, x64, Eclipse.Mars

When a docker host is not configured to use Key Vault, the error message displayed in the Details dialog is inaccurate
![kv](https://cloud.githubusercontent.com/assets/21356612/24973136/94c6b6aa-1f72-11e7-836b-7d1562222b63.PNG)
:

**Comment by martinsawicki** [comment]
no exclamation marks in user messages

**Comment by milismsft** [comment]
Not repro; if the Docker host was indeed created without being associated with a key vault, the expected message captures that. In the case above the issue is that we attempted to create a key vault for the docker host but we failed to do so and the association is still there. 

To remove the association is a bit more challenging because there are a lot of conditions to be met. The user can reset the default credentials we created for m and at that time we will also remove this association.

**Comment by bsaby** [comment]
Test passed, using artifacts/azure-toolkit-for-intellij.2017.342.04-19-2017.zip.
If the Docker Host does not have a key vault association, thecontent of  Key Vault settings displays "Not using Key Vault".Shown as below picture.
![image](https://cloud.githubusercontent.com/assets/22470312/25213251/e7100b5a-25c1-11e7-98b0-32d8fb54936a.png)

**Comment by bsaby** [comment]
Test passed, using artifacts/WindowsAzurePlugin4EJ.348.04-19-2017.zip
.
If the Docker Host does not have a key vault association, thecontent of Key Vault settings displays "Not using Key Vault".
Shown as below picture:
![image](https://cloud.githubusercontent.com/assets/22470312/25213498/969e5e4a-25c3-11e7-868e-86e8615a4fe7.png)
