### ISSUE TITLE
Application Insights  can't return to the resource in Microsoft Azure

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#354]
After configuring Application Insights, everything seems ok, but run your application, the data will not return to resource in Microsoft Azure.

**Comment by lenala** [comment]
Just checked with IntelliJ 2016 and the released build - worked for me, I am able to see requests in AppInsights on Azure. Might be because data processing is delayed, you may also try to change  to    <DeveloperMode>true</DeveloperMode> in ApplicationInsights.xml to get the data faster. I had to wait about 5 minutes to see results.

**Comment by bsaby** [comment]
Test passed in IntelliJ2017.1.1, using artifacts/azure-toolkit-for-intellij.2017.348.04-20-2017.zip.
 **Failed in Eclipse**, using artifacts/WindowsAzurePlugin4EJ.349.04-19-2017.zip.
After configuring Application Insights,  run your application, everything seems ok in Eclipse, but after a long time, the data has not been returned to resource in Microsoft Azure.

**Comment by lenala** [comment]
Worked for me in Eclipse, I tried several times. There was about 10 minutes delay in displaying data, but after some time I was able to see it.
I used our build that was released yesterday, installing from update site http://dl.microsoft.com/eclipse .

**Comment by bsaby** [comment]
Test passed in the released build from above site. 
So, close this issue or continue to investigate the issue on our latest build?

**Comment by bsaby** [comment]
Test passed in latest build for Eclipse: artifacts/WindowsAzurePlugin4EJ.383.04-26-2017.zip.
