### ISSUE TITLE
[intelliJ][19.3 EAP]Unreasonable display when select "Edit '[Spark on ***]' "

### ISSUE THREAD

**Issue by v-jiche** [microsoft/azure-tools-for-java#3710]
Build:
azure-toolkit-for-intellij-LATEST-EAP-SNAPSHOT.develop.10727955.10-24-2019

Repro Steps:
1. Create a new project.
2. Set default Spark Application Type as HDInsight.
3. Right click LogQuery then select locally run.
4. Set default Spark Application Type as Cosmos.
5. Right click LogQuery then select submit Spark application, then click SparkJobRun/Continue Anyway.
6. Right click LogQuerly then select "Edit '[Spark on HDInsight]...' ".
![无标题](https://user-images.githubusercontent.com/35950097/68014436-8e269f80-fcca-11e9-82c9-d2bb224052ab.png)

Result:
Edit Run Configuration window is opened.
However, "Spark on cosmos" shows out.
![image](https://user-images.githubusercontent.com/35950097/68014464-a8607d80-fcca-11e9-8595-185d1088ae71.png)

**Comment by v-lanjli** [comment]
Fixed in this build (https://dev.azure.com/mseng/_apis/resources/Containers/11319627?itemPath=drop%2Fazure-toolkit-for-intellij-LATEST-EAP-SNAPSHOT.develop.11021963.12-04-2019.zip)
![image](https://user-images.githubusercontent.com/40199316/70122540-ca736400-16ab-11ea-9a4a-f9fc40f78060.png)
And closed this issue.
