### ISSUE TITLE
Eclipse - can't add Microsoft Azure Libraries to Java path

### ISSUE THREAD

**Issue by ronny-sphera** [microsoft/azure-tools-for-java#4448]
When trying to add the package to the build path, an error is displayed: "The selected version is not available".

Steps taken:
1. Downloaded and installed latest version of Azure Toolkit for Eclipse from the Eclipse Marketplace
2. Right-clicked on project -->Properties --> Java Build Path --> Add Library
3. Selected "Package for Microsoft Azure Libraries for Java" --> Next
4. The following window is displayed:
![image](https://user-images.githubusercontent.com/66822471/84481809-91393380-ac8e-11ea-9cf8-9a9ab75b6a8f.png)

**Comment by Flanker32** [comment]
@ronny-sphera Thanks for your report, will looking into this issue soon.

**Comment by bvkavya** [comment]
I am also facing the same issue. Is there any update?

**Comment by Flanker32** [comment]
@bvkavya Sorry but i'm still working on this issue, i'll update here once there are updates.

**Comment by Flanker32** [comment]
@ronny-sphera @bvkavya Thanks for your report, the issue has been fixed in #4512, and will be available in v3.24.0. Before the new release, you may fallback to v3.22.0 as a workaround, you may get the document [here](https://docs.microsoft.com/en-us/azure/developer/java/toolkit-for-eclipse/installation#install-new-software) and the url is `https://azuredownloads.blob.core.windows.net/eclipse/v3.22.0/`

**Comment by Flanker32** [comment]
@ronny-sphera @bvkavya Thanks for your report, Eclipse v3.24.0 has been released, you may get it from the Eclipse marketplace.
