### ISSUE TITLE
Resource creation should not be blocking

### ISSUE THREAD

**Issue by akaroml** [microsoft/azure-tools-for-java#4723]
![Screen Shot 2020-11-05 at 3 39 19 PM](https://user-images.githubusercontent.com/16755094/98211511-20682000-1f7d-11eb-93f5-81f43a5478f2.png)

When creating a web app, the users are blocked by the progress dialog. This should be a task that does NOT block the users.

**Comment by Flanker32** [comment]
@akaroml Thanks for your help and feedback!
We made the web app creation action here as a foreground action in case creation failed with reasons like quota used up, so that we could back to the creation dialog and users could fix the parameters with the error prompt. 
If we make the action a background task, the task will failed directly, users need to trigger the action and fill the parameters again.

**Comment by Flanker32** [comment]
Solved in https://github.com/microsoft/azure-tools-for-java/pull/4868/files, foreground task could be send to background now
