### ISSUE TITLE
doc says once you ready, right click on project to publish web-app in azure,  but publish web-app is disabled unless you manually sign in from tools menu

### ISSUE THREAD

**Issue by arroyc** [Microsoft/azure-tools-for-java#53]
![image](https://cloud.githubusercontent.com/assets/16231002/23077255/a657c6a6-f4f8-11e6-9317-ca6b1484fd63.png)

**Comment by martinsawicki** [comment]
doc update

**Comment by martinsawicki** [comment]
actually not docs -- we have another issue where we are going to enable this command and prompt for log in as needed

**Comment by bsaby** [comment]
Where can I find the doc? 
Seems not this one: https://docs.microsoft.com/en-us/azure/app-service-web/app-service-web-intellij-create-hello-world-web-app

**Comment by martinsawicki** [comment]
Basically, the issue is that in an earlier build, Publish As Web App was disabled until you logged in. But the idea is for Publish Web App to be enabled (like in the past), and simply prompt for log-in as needed.
(I think the "doc" referred to in this bug was the temporary docs provided for the bug-bash.)

**Comment by bsaby** [comment]
It has been implemented that Publish As Web App to be enabled and simply prompt for log-in as needed.
Test passed in #101 .
