### ISSUE TITLE
IntelliJ editor Fatal error while deploying to docker container

### ISSUE THREAD

**Issue by anuchandy** [Microsoft/azure-tools-for-java#92]
During the process of publishing to docker container, IntelliJ showed a small warning popup box and expanding that showed below message.  This is not a blocking issue, just warning.

![idefatalerror](https://cloud.githubusercontent.com/assets/1471612/23079959/e906d05e-f503-11e6-8852-59c799591a84.png)

**Comment by anuchandy** [comment]
Notice that the path to the web app is wrong (there is a colon in the name)

**Comment by milismsft** [comment]
no repro

**Comment by martinsawicki** [comment]
ready for test

**Comment by bsaby** [comment]
Repro.
Now if the name is illegal, the error message is not prompted until you click "Published" in Azure Aztivity Log, actually the web app in container is not published successfully. 
![image](https://cloud.githubusercontent.com/assets/22470312/24694447/7dec9c8c-1a14-11e7-85e0-1a96e36310bc.png)

**Comment by milismsft** [comment]
Should be fixed now; if the default artifact filename does not pass the validation, we now display an empty string

**Comment by bsaby** [comment]
Repro, using artifacts/azure-toolkit-for-intellij.2017.228.04-06-2017.zip.

- If the default artifact filename is illegal, the folder location is blank with a red exclamation mark (picture 1).

- But after manually select the artifact file with illegal name, it can still be published because **Next** and **Finish** button are still available(picture 2). 

- And the error message will be  prompted when you click "Published" in Azure Aztivity Log(picture 3).

**picture 1:**
![image](https://cloud.githubusercontent.com/assets/22470312/24783506/631a6e54-1b7f-11e7-9a41-c9124fc69b6f.png)
**picture 2:**
![image](https://cloud.githubusercontent.com/assets/22470312/24783246/b7227124-1b7d-11e7-8c42-e4bd70ded261.png)
**picture 3:**
![image](https://cloud.githubusercontent.com/assets/22470312/24783573/be5b43ce-1b7f-11e7-805c-fc758605a6ab.png)

**Comment by milismsft** [comment]
Good catch; it should be fixed in the latest. Keep in mind though that in IntelliJ the validation will happen when the user clicks Next or Finish rather then when he exits the browse dialog (that's how the control works).

**Comment by bsaby** [comment]
Test passed， using azure-toolkit-for-intellij.2017.240.04-09-2017.zip.
If the default artifact filename is illegal, there will be a prompt.
![image](https://cloud.githubusercontent.com/assets/22470312/24847795/e32a7d50-1df5-11e7-8a51-dbc5817e6dc2.png)
