### ISSUE TITLE
check view before error handling

### ISSUE THREAD

**Issue by Eskibear** [Microsoft/azure-tools-for-java#924]
in `WebAppOnLinuxDeployPresenter`, should check `isViweDetached` before error handling.

**Comment by jdneo** [comment]
And the presenter should detach the view when the run configuration editor is disposed.

**Comment by jdneo** [comment]
Repro step:

1. open azure web app run configuration
2. choose create
3. disconnect the network and switch the subscription
4. close the run configuration dialog

Expect: 
Because the dialog is closed, a error msg caused by network error should not be popped up.

Result:
After a while, a error msg caused by network error popped up.

**Comment by jdneo** [comment]
@bsaby Fixed, please help verify it in the new build, thanks. (For both web app and web app on linux run configuration)

**Comment by bsaby** [comment]
Test passed on both Azure Web App and Web App(Linux).
Build used: dev321
